[build-system]
requires = ["setuptools>=65.5", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "telegram-transcript-exporter"
version = "0.1.0"
description = "Utility for exporting Telegram transcripts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "telethon==1.42.0",
    "python-dotenv==1.2.1",
]

[project.optional-dependencies]
dev = [
    "ruff==0.14.9",
    "pytest>=9.0.2",
    "uv",
]

[project.scripts]
telegram-transcript-exporter = "main:main"

[tool.ruff]
line-length = 120
target-version = "py312"
fix = false

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"__future__.annotations".msg = "Drop `from __future__ import annotations` (target Python ≥ 3.12)."

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
    "E402",
    "PLC0415",
    "TID",
    "UP",
    "I",
    "B",
    "C4",
    "SIM",
    "ARG",
    "N",
    "RUF",
    "RET",
    "COM",
    "YTT",
]

ignore = [
    "COM812",
]

[tool.pytest.ini_options]
pythonpath = ["."]
